### ISSUE TITLE
Error during rendering with docusaurus

### ISSUE THREAD

**Issue by anatoly-kryzhanovsky** [likec4/likec4#1774]
we use likec4 with docusaurus
we use version 1.18 a long and then we deside to upgrade to actual version we received error: `render is not a function`
i'll investigate that error occurs after upgrade from 1.22.1 to 1.23.0
also we found that if we upgrade react to 1.19.x errors has gone, but many of other out components does not support react 1.19
i found that likec4 should be compatible with react 1.18 and 1.19 but something goes wrong

can you verify that all works with react 1.18?

**Comment by davydkov** [comment]
Hi @anatoly-kryzhanovsky 

Can you verify these prereleases?

```sh
# Add @likec4/core:
npm i https://pkg.pr.new/likec4/likec4/@likec4/core@f9ff067

# Add likec4:
npm i https://pkg.pr.new/likec4/likec4@f9ff067
```

I've marked react as peer-dependency with `18.x || 19.x` range

**Comment by davydkov** [comment]
Release [1.28.1](https://github.com/likec4/likec4/releases/tag/v1.28.1) has `18.x || 19.x` react compatibility 

Reopen if you are still experiencing this issue

**Comment by anatoly-kryzhanovsky** [comment]
ok, i will check it at Monday and return with feedback, thanks!

**Comment by anatoly-kryzhanovsky** [comment]
i try to use 1.28.1 but error still here

```
render is not a function
TypeError: render is not a function
    at updateContextConsumer (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21241:19)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21686:14)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4213:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4277:31)
    at beginWork$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27485:7)
    at performUnitOfWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26594:12)
    at workLoopSync (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26500:5)
    at renderRootSync (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26468:7)
    at performSyncWorkOnRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26119:20)
```
