### ISSUE TITLE
API: elements is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by 304NotModified** [likec4/likec4#2537]
### Relates to

LikeC4 Language

### Version you are using

1.47

### Describe the issue

For some reason, we get with this code in 1.47

> c4Model.elements is not a function or its return value is not iterable

```ts
export function getUniqueMetadataElements(c4Model:LikeC4Model, metadataElementKey:string) : Array<string> {
    return [...new Set<string>([...c4Model.elements()]
```

This works in 1.46.2.
Any idea what the problem is?

We have many many likec4 models and I don't know what is triggering this issue.

**Comment by davydkov** [comment]
Hey @304NotModified 
Thanks for reporting, gonna check this asap

**Comment by davydkov** [comment]
@304NotModified we are same city, lets have a beer some day 🍺

**Comment by davydkov** [comment]
Hey @304NotModified 

How did you get your instance or `c4Model`? Builder, generated, vite plugin?

**Comment by davydkov** [comment]
Assume it is solved
